name: Freeze bot

on:
  pull_request:
    types: [opened, reopened]
  issue_comment:
    types: [created]

jobs:
  refreeze:
    runs-on: ubuntu-latest
    steps:
      - name: Get upstream
        if: contains(github.event.comment.html_url, '/pull/')
        run: |
          # A useful wrapper around CURL
          crl() {
            curl --silent --show-error --location --retry 1 "${@:2}" \
              -H "Accept: application/vnd.github.github.sailor-v-preview, application/vnd.github.v3+json" \
             "$1"
          }
          auth_crl() {
            crl "$1" -H "authorization: Bearer $GITHUB_TOKEN" "${@:2}"
          }
          echo "::set-env name=BRANCH_NAME::$(curl -v -H "Accept: application/vnd.github.sailor-v-preview+json" -u ${{ secrets.GITHUB_TOKEN }} ${{ github.event.issue.pull_request.url }} | jq '.head.ref' | sed 's/\"//g')"
          echo ${{ github.repository }}
          echo ${{ github.ref}}

      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: Set Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install deps
        run: |
          python -m pip install --upgrade pip ruamel.yaml

      - name: Monitor comments
        if: contains(github.event.comment.html_url, '/pull/')
        run: |
          python ./scripts/freeze-bot.py
          echo ${{ github.event.issue.pull_request.url }}
          echo ${{ github.event.issue.pull_request.head.repo.full_name }}

        env:
          BOT_PHRASE: "@bot please refreeze"
        id: prcomment

      - name: To freeze or not to freeze
        if: env.TRIGGER_ACTION == 'True'
        run: |
          echo "Re-freeze triggered by ${NAME}"
          python repo2docker/buildpacks/conda/freeze.py "3.8"

      - name: Commit the re freezed buildpack
        if: env.TRIGGER_ACTION == 'True'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github actions bot"
          git add ${{ github.workspace }}/repo2docker/buildpacks/conda/
          git commit -m "Refreezed conda buildpack"
          git push -q -f https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} ${{ env.BRANCH_NAME }}

      - name: Add comment
        if: env.TRIGGER_ACTION == 'True'
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Refeeze completed. Check the lst commit before merge.'
            })
